### ISSUE TITLE
npm run build doesn't work

### ISSUE THREAD

**Issue by sclausen** [DanielYKPan/date-range-picker#4]
I freshly cloned this repo and after `npm i` I ran `npm run build` and the following error occurs:

    > ng-pick-daterange@1.0.0 build /home/username/git/DanielYKPan/date-range-picker
    > rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail

      0% compilingEntryModuleNotFoundError: Entry module not found: Error: Can't resolve './src/polyfills.ts' in '/home/username/git/DanielYKPan/date-range-picker'
        at moduleFactory.create (/home/username/git/DanielYKPan/date-range-picker/node_modules/webpack/lib/Compilation.js:362:29)
        at /home/username/git/DanielYKPan/date-range-picker/node_modules/webpack/lib/NormalModuleFactory.js:234:19
        at onDoneResolving (/home/username/git/DanielYKPan/date-range-picker/node_modules/webpack/lib/NormalModuleFactory.js:59:20)
        at /home/username/git/DanielYKPan/date-range-picker/node_modules/webpack/lib/NormalModuleFactory.js:126:20
        at /home/username/git/DanielYKPan/date-range-picker/node_modules/async/dist/async.js:3838:9
        at /home/username/git/DanielYKPan/date-range-picker/node_modules/async/dist/async.js:421:16
        at iteratorCallback (/home/username/git/DanielYKPan/date-range-picker/node_modules/async/dist/async.js:996:13)
        at /home/username/git/DanielYKPan/date-range-picker/node_modules/async/dist/async.js:906:16
        at /home/username/git/DanielYKPan/date-range-picker/node_modules/async/dist/async.js:3835:13
        at /home/username/git/DanielYKPan/date-range-picker/node_modules/webpack/lib/NormalModuleFactory.js:121:22
        at onResolved (/home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/Resolver.js:70:11)
        at loggingCallbackWrapper (/home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
        at afterInnerCallback (/home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
        at loggingCallbackWrapper (/home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
        at Resolver.applyPluginsAsyncSeriesBailResult1 (/home/username/git/DanielYKPan/date-range-picker/node_modules/tapable/lib/Tapable.js:181:46)
        at innerCallback (/home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
        at loggingCallbackWrapper (/home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
        at /home/username/git/DanielYKPan/date-range-picker/node_modules/tapable/lib/Tapable.js:283:15
        at /home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/UnsafeCachePlugin.js:38:4
        at loggingCallbackWrapper (/home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
        at afterInnerCallback (/home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/Resolver.js:138:10)
        at loggingCallbackWrapper (/home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
        at Resolver.applyPluginsAsyncSeriesBailResult1 (/home/username/git/DanielYKPan/date-range-picker/node_modules/tapable/lib/Tapable.js:181:46)
        at innerCallback (/home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/Resolver.js:125:19)
        at loggingCallbackWrapper (/home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
        at /home/username/git/DanielYKPan/date-range-picker/node_modules/tapable/lib/Tapable.js:283:15
        at innerCallback (/home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/Resolver.js:123:11)
        at loggingCallbackWrapper (/home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/createInnerCallback.js:31:19)
        at /home/username/git/DanielYKPan/date-range-picker/node_modules/tapable/lib/Tapable.js:283:15
        at resolver.doResolve.createInnerCallback (/home/username/git/DanielYKPan/date-range-picker/node_modules/enhanced-resolve/lib/DescriptionFilePlugin.js:44:6)
    resolve './src/polyfills.ts' in '/home/username/git/DanielYKPan/date-range-picker'
      using description file: /home/username/git/DanielYKPan/date-range-picker/package.json (relative path: .)
        Field 'browser' doesn't contain a valid alias configuration
      after using description file: /home/username/git/DanielYKPan/date-range-picker/package.json (relative path: .)
        using description file: /home/username/git/DanielYKPan/date-range-picker/package.json (relative path: ./src/polyfills.ts)
          as directory
            /home/username/git/DanielYKPan/date-range-picker/src/polyfills.ts doesn't exist
          no extension
            Field 'browser' doesn't contain a valid alias configuration
            /home/username/git/DanielYKPan/date-range-picker/src/polyfills.ts doesn't exist
          .ts
            Field 'browser' doesn't contain a valid alias configuration
            /home/username/git/DanielYKPan/date-range-picker/src/polyfills.ts.ts doesn't exist
          .js
            Field 'browser' doesn't contain a valid alias configuration
            /home/username/git/DanielYKPan/date-range-picker/src/polyfills.ts.js doesn't exist
          .json
            Field 'browser' doesn't contain a valid alias configuration
            /home/username/git/DanielYKPan/date-range-picker/src/polyfills.ts.json doesn't exist

    npm ERR! Linux 4.4.0-75-generic
    npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "build"
    npm ERR! node v6.10.3
    npm ERR! npm  v3.10.10
    npm ERR! code ELIFECYCLE
    npm ERR! ng-pick-daterange@1.0.0 build: `rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the ng-pick-daterange@1.0.0 build script 'rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the ng-pick-daterange package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     rimraf dist && webpack --config config/webpack.prod.js --progress --profile --bail
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs ng-pick-daterange
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls ng-pick-daterange
    npm ERR! There is likely additional logging output above.

    npm ERR! Please include the following file with any support request:
    npm ERR!     /home/username/git/DanielYKPan/date-range-picker/npm-debug.log

**Comment by jessenic** [comment]
Same problem here, I forked this to fix some issues but I don't know how to build it, never worked on module packages before.
